# Generated by Django 3.1.3 on 2020-12-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20201207_1042'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='inscrito_em',
            field=models.ManyToManyField(blank=True, related_name='inscritos', to='eventos.Evento'),
        ),
        migrations.AddField(
            model_name='participante',
            name='presente_em',
            field=models.ManyToManyField(blank=True, related_name='presentes', to='eventos.Evento'),
        ),
    ]
