# Generated by Django 3.1.3 on 2020-12-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201207_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='inscrito_em',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='presente_em',
        ),
    ]
