# Generated by Django 3.1.3 on 2020-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201207_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='extraQuestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
