# Generated by Django 3.1.3 on 2020-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('empresa', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('aberto', models.BooleanField(default=False)),
            ],
        ),
    ]
