# Generated by Django 3.1.3 on 2020-11-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='inicio evento')),
                ('fim', models.DateTimeField(verbose_name='fim evento')),
                ('tema', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('empresa', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
    ]
