# Generated by Django 3.1.3 on 2020-12-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='inscritos', to='users.Participante'),
        ),
    ]
