# Generated by Django 3.1.3 on 2020-12-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20201206_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='aberto',
            new_name='abertoParticipar',
        ),
        migrations.AddField(
            model_name='evento',
            name='abertoFeedback',
            field=models.BooleanField(default=False),
        ),
    ]
