# Generated by Django 3.1.3 on 2020-12-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('eventos', '0004_auto_20201206_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='presentes',
            field=models.ManyToManyField(blank=True, related_name='presente_em', to='users.Participante'),
        ),
    ]
