# Generated by Django 3.1.3 on 2020-12-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_evento_presentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='inscritos',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='presentes',
        ),
    ]
