# Generated by Django 3.1.3 on 2020-12-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201207_1046'),
        ('eventos', '0006_auto_20201207_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='inscrito_em', to='users.Participante'),
        ),
        migrations.AddField(
            model_name='evento',
            name='presentes',
            field=models.ManyToManyField(blank=True, related_name='presente_em', to='users.Participante'),
        ),
    ]
