# Generated by Django 3.1.3 on 2020-12-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('eventos', '0003_auto_20201206_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectativa', models.IntegerField(choices=[(0, '0 (Nada)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, '10 (Muito)')], help_text='Sendo 0 = "Não gostei nada" e 10 = "Amei tudo"', verbose_name='Quanto o evento atendeu às suas expectativas?')),
                ('tema', models.IntegerField(choices=[(0, '0 (Nada)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, '10 (Muito)')], help_text='Sendo 0 = "Não gostei nada" e 10 = "Amei tudo"', verbose_name='Quanto você gostou do tema do evento?')),
                ('organização', models.IntegerField(choices=[(0, '0 (Nada)'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, '10 (Muito)')], help_text='Sendo 0 = "Não gostei nada" e 10 = "Amei tudo"', verbose_name='Quanto você gostou da organização do evento?')),
                ('extraQuestions', models.JSONField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.participante')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'autor')},
            },
        ),
    ]
