# Generated by Django 3.1.3 on 2020-12-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comentários',
            field=models.TextField(blank=True, null=True, verbose_name='Comentários gerais sobre o evento:'),
        ),
    ]
