# Generated by Django 3.1.3 on 2020-12-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20201207_1046'),
        ('feedback', '0002_feedback_comentários'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntafeedback',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_feedback', to='eventos.evento'),
            preserve_default=False,
        ),
    ]
