# Generated by Django 3.1.3 on 2020-12-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.IntegerField(help_text='Meta de presenças para ganhar')),
                ('premio', models.CharField(max_length=100)),
                ('ganhadores', models.ManyToManyField(blank=True, related_name='ganhou_premio', to='users.Participante')),
            ],
        ),
    ]
